config/routes.rb
OwenTasks::Application.routes.draw do
  get "today" => "today#index", :as => "today"

  get "index" => "pages#index", :as => "index"
  get "new_task" => "tasks#new", :as => "new_task"

  get "about" => "pages#about", :as => "about"
  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"

  get "sign_up" => "users#new", :as => "sign_up"
  
  root :to => "pages#index"

  resources :users
  resources :sessions
  resources :tasks
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation
  
  has_many :tasks

  attr_accessor :password
  before_save :encrypt_password

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    end
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user


  private
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.authenticate(params[:email], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to today_path, :notice => "Welcome #{user.email}! You have sucessfully logged in!"
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to log_in_path, :notice => "You have sucessfully logged out from your account!"
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def new
    @task = Task.new
  end

  def create
    @task = Task.new(params[:task])
    @task.user_id = session[:user_id]
    if @task.save
      redirect_to today_path, :notice => "Task saved!"
    else
      render "new"
    end
  end
end

app/controllers/today_controller.rb
class TodayController < ApplicationController
  def index
    @user = current_user
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to root_url, :notice => "Signed Up!"
    else
      render "new"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/today_helper.rb
module TodayHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer><p>Copyright 2011 - Crisostomo, Divinagracia, Landa</p></footer>

app/views/layouts/_header.html.erb
<header>
<% logo = image_tag("logo.png", :alt => "OwenTasks", :class => "round") %>
  <%= link_to logo, root_path %>
    <nav>
    <ul>
      <% if current_user  %>
	<li><%= link_to "New Task", new_task_path %> <%= link_to "Task HQ", today_path %> <%= link_to "Log out", log_out_path %></li><br />
        Logged in as <%= current_user.email %>
      <% else  %>
        <li><%= link_to "Home", root_path %> <%= link_to "Sign up", sign_up_path %> 
	 <%= link_to "About Us", about_path %> <%= link_to "Log in", log_in_path %></li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!-- [if lt IE 9]>
  <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"</script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print', :media => 'print' %>
<!-- [if lt IE 8]> <%= stylesheet_link_tag 'blueprint/ie' %> <![endif]-->
<%= stylesheet_link_tag 'default', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OwenTasks</title>
    <%= csrf_meta_tag %>
    <%= render 'layouts/stylesheets' %>
  </head>
  <body>
    <div class="container">
      <%= render 'layouts/header' %>
       <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}"%>
      <% end %> 
      <section>
	<%= yield %>
      </section>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<header>

	<h3>About Owentasks</h3>
	<p>
	    OwenTasks is a Project currently being developed by a team of curious minds. the idea and concept<br />
	    comes from these young men, namely: John Crisostomo - Great and Benevolent Leader, Joanel Divinagracia - The Man With some Plan<br />
	    Arveen Landa - Man with the arts and creative juices overflowing.<br /><br />

	    Currently OwenTasks is still in Beta Phase and isn't Open to the public. Except for some people.<br />
	    for testing purposes. As Stated It is still under testing and can be Buggy. The Developers will be trying<br />
	    to build and improve the current contents while going on with their daily lives as students.

	    
	</p>

	<h3>The Developers</h3>	
 	
	<p>
	<%= image_tag("jed.jpg", :alt => "John Crisostomo", :size => "300x400") %><br />
	Name: John Crisostomo<br />
	Contact No: 4924957<br />
	Email: 4r5c4r105u5@gmail.com<br />
	Twitter: @arscariosus<br />
	    John Crisostomo is The Man in Power, The CEO and Project Leader of OwenTasks.<br />
	    His Contributions are of importance aside from conceptualization. He is known <br />
	    for supporting F.O.S.S. and is a seasoned Ruby on Rails Programmer.
	</p>

	<p>
	<%= image_tag("joanel.jpg", :alt => "Joanel Divinagracia", :size => "300x400") %><br />
	Name: Joanel Divinagracia<br />
	Contact No: 7436543<br />
	Email: joaneldivinagracia@gmail.com<br />
	Twitter: @iamanepichero<br />
	   Joanel Divinagracia is adviser to John Crisostomo and co-colaborator.<br />
	   This colaboration is a first for this team up, and while he is a rookie<br />
	   when it comes to Ruby on Rails, he believes that this is part of the learning process.
	</p>
	
	
	<p>
	<%= image_tag("arveen.jpg", :alt => "Arveen Landa", :size => "300x400") %><br />
	Name: Arveen Landa<br />
	Contact No: 7653311<br />
	Email: aml@yahoo.com<br />
	Twitter: @arveen11<br />
	    Arveen Landa is the man responsible for some aesthetic's and improvement when it comes to<br />
	    Design. He is also in responsible for the project documentation and other paper works.
	</p>


	<p>
	  Again we Welcome you to OwenTasks, Thank You for Being Patient with us - arscariosus, iamanepicHERO, Conan.
	</p>

app/views/pages/index.html.erb
<h1>Welcome to OwenTasks!</h1>

<p>
Do you usually forget what you need to  do?<br>
Forget Certain Tasks of Importance??<br>
OwenTasks is Here to Assist you with your woes!
</p>

<%= link_to "Sign up now!", 'sign_up', :class => "signup_button round" %>

app/views/tasks/new.html.erb
<h1>Add new task</h1>

<%= form_for @task do |f| %>
  <p>
    <%= f.label :task %>
    <%= f.text_field :task  %>
  </p>
  <p>
    <%= f.label :due_on %>
    <%= f.date_select :due  %>
  </p>
  <p>
    <%= f.submit  %>
  </p>
<% end  %>

app/views/today/index.html.erb
<div class="tasks">

  <h2>Today's Tasks</h2>
  <% for task in @user.tasks %>
  <ul  class="lines">
    <li><%= task.task %><br />
    Due on <%= task.due %></li>
  </ul>
  <% end %>
</div>

app/views/users/new.html.erb
<header>
<h1>Sign Up</h1>
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
	<% for message in @user.errors.full_messages %>
	  <li><%= message %></li>
	<% end  %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :email %><br >
    <%= f.text_field :email %>
  </p>

  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>

  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>

  <p class="button"><%= f.submit %></p>
<% end %>